---
- name: Decrypt, extract, and clean up backup files
  hosts: localhost
  gather_facts: no
  vars:
    backup_dir: "{{ lookup('env', 'PWD') }}"  # Get the current directory from environment variables
    encrypt_pass_file: "$HOME/.dotfiles/.env/encrypt_pass"

  tasks:
    - name: Find encrypted backup files
      find:
        paths: "{{ backup_dir }}"
        patterns: "*.dir.tar.gz"
      register: encrypted_files

    - name: Decrypt each backup file
      command:
        cmd: "ansible-vault decrypt {{ item.path }} --vault-password-file {{ encrypt_pass_file }}"
      with_items: "{{ encrypted_files.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Extract each archive
      command:
        cmd: "tar -xzf {{ item.path }} -C {{ backup_dir }}"
      with_items: "{{ encrypted_files.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Delete the decrypted archive
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ encrypted_files.files }}"
      loop_control:
        label: "{{ item.path }}"

